### ISSUE TITLE
Error related to React v16

### ISSUE THREAD

**Issue by x5engine** [webhacking/url-metadata-parser#2] opened 2019-04-20 23:16 UTC
Error related to React v16

```
node_modules/url-metadata-parser/dist/url-metadata-parser.js:26
        ].map(([c, bytes]) => {
                                             ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/workspace/Vulcan/node_modules/url-metadata-parser/dist/index.js:3:31)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
Exited with code: 1
Your application is crashing. Waiting for file change.
```

**Comment by webhacking** [comment] 2019-04-22 08:28
Duplicate of #1

**Closed by webhacking** 2019-04-22 08:28 UTC
